version: '2'
services:
  jm-memcached1:
    image: memcached
  jm-memcached2:
    image: memcached
  jm-memcached3:
    image: memcached

  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    working_dir: /application
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../:/application
    container_name: jm-nginx

  php-fpm:
    build: ./php-fpm
    links:
      - jm-memcached1
      - jm-memcached2
      - jm-memcached3
    volumes:
      - ../:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    container_name: jm-php-fpm
